apiVersion: v1
kind: Service
metadata:
    name: "k8stestdev-cb57"
    labels:
        app: "k8stestdev-cb57"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "k8stestdev-cb57"